Warner.Reportage/ViewModels/BuildViewModel.cs
using System;
using Warner.Domain;
using Warner.Reportage.ViewModels.Factories;

namespace Warner.Reportage.ViewModels
{
    public class BuildViewModel
    {
        private readonly Build model;

        public BuildViewModel(Build model)
        {
            this.model = model ??
                throw new ArgumentNullException(nameof(model));
        }

        public string BuildNumberDisplay
        {
            get
            {
                return $"#{model.BuildNumber}";
            }
        }

        public DateTimeOffset BuildDateDisplay
        {
            get
            {
                return model.BuildDate;
            }
        }

        public Build Model => model;

        public string TimeAmountSinceBuilt
        {
            get
            {
                var amount = new NiceTimeAmount(
                    Model.BuildDate,
                    DateTimeOffset.Now);
                return amount.GetDisplayValue();
            }
        }
    }
}

Warner.Reportage/Controllers/BuildsController.cs
using System;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Warner.Reportage.DomainServices;
using Warner.Reportage.ViewModels;
using Warner.Reportage.ViewModels.Factories;

namespace Warner.Reportage.Controllers
{
    public class BuildsController : Controller
    {
        private readonly IBuildsService builds;
        private readonly IWarningService warnings;

        public BuildsController(
            IBuildsService builds,
            IWarningService warnings)
        {
            this.builds = builds;
            this.warnings = warnings;
        }

        public IActionResult Index(string projectName)
        {
            var model = builds
                .GetAllForProject(projectName)
                .Select(p => new BuildViewModel(p));
            // let's process only 7 latest builds
            var top7 = model.OrderByDescending(m => m.BuildDateDisplay).Take(7);
            return View(top7);
        }

        public IActionResult Details(int buildId)
        {
            var viewModel = new BuildDetailsViewModelFactory(builds, warnings)
                .Create(buildId);
            return View(viewModel);
        }
    }
}

Warner.Reportage/Controllers/WarningsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using Warner.Domain;
using Warner.Reportage.DomainServices;
using Warner.Reportage.ViewModels;

namespace Warner.Reportage.Controllers
{
    public class WarningsController : Controller
    {
        private readonly IWarningService warningService;

        public WarningsController(IWarningService warningService)
        {
            this.warningService = warningService;
        }

        public IActionResult Stats(long buildId)
        {
            IEnumerable<BuildWarning> warnings =
                warningService.AllForBuild(buildId);
            var viewModel = new BuildStatsViewModel(warnings.ToList());
            return View(viewModel);
        }

        public IActionResult DetailsForType(string warningType, long buildId)
        {
            IEnumerable<BuildWarning> warnings =
                warningService.AllForBuildOfType(buildId, warningType);
            var viewModel = new WarningOfTypeForBuildDetailsViewModel(warnings);
            return View(viewModel);
        }
    }
}

Warner.Reportage/Views/Builds/Details.cshtml
@using Warner.Reportage.ViewModels
@model BuildDetailsViewModel

@{
    ViewBag.Title = "Build warnings";
    int totalDynamic = Model.WarningsTotalCountCurrent - Model.WarningsTotalCountPrevious;
}

<h2>Build has @Model.WarningsTotalCountCurrent warnings (
    @if (totalDynamic < 0)
    {
        <span style="color: green;">↓@Math.Abs(totalDynamic)</span>
    }
    else
    {
        <span style="color: red;">↑@Math.Abs(totalDynamic)</span>
    })
</h2>

<div class="col-md-4">
    <h3>Warnings by count:</h3>
    <ul>
        @foreach (var v in Model.Summary.ToList().OrderByDescending(p => p.Value))
        {
            string warningType = v.Key;
            <li>
                <span>
                    @{ string link = new WarningLinkProvider(warningType).GetLink(); }
                    <a href="@link">@warningType</a>
                </span>
                <span>
                    @Model.Summary[warningType]
                </span>
            </li>
        }
    </ul>
</div>
<div class="col-md-8">
    <h3>Warnings movement:</h3>
    <ul>
        @foreach (var pair in Model.WarningMovements.OrderByDescending(b => Math.Abs(b.Value)))
        {
            string warningType = pair.Key;
            int warningMovement = pair.Value;
            int warningsCount = Model.Summary.ContainsKey(warningType) ? Model.Summary[warningType] : 0;
            <li>
                <div>
                    <span>
                        @{ string link = new WarningLinkProvider(warningType).GetLink(); }
                        <span><a href="@link">@warningType</a></span>
                        <span>:</span>
                        @if (warningMovement > 0)
                        {
                            <span style="color: red;">@String.Format($"+{warningMovement}")</span>
                        }
                        else if (warningMovement < 0)
                        {
                            <span style="color: green;">@String.Format($"{warningMovement}")</span>
                        }
                    </span>
                    <span>
                        now have @Html.ActionLink(warningsCount.ToString(), "DetailsForType", "Warnings", new { WarningType = warningType, Model.BuildId })
                    </span>
                </div>
            </li>
         }
    </ul>
</div>




Warner.Reportage/Views/Builds/Index.cshtml
@using Warner.Reportage.ViewModels
@model IEnumerable<BuildViewModel>

@{
    ViewBag.Title = "Builds available";
}

<h1>
    Latest @Model.Count() tracked builds
</h1>
<ul>
    @foreach (BuildViewModel buildViewModel in Model)
    {
        <li class="no-bullet">
            <h3>
                @Html.ActionLink(@buildViewModel.BuildNumberDisplay,
                    "Details",
                    "Builds",
                    new { buildId = @buildViewModel.Model.Id },
                    new { @class = "build-link" })

            </h3>
            <span>
                @buildViewModel.TimeAmountSinceBuilt ago
            </span>
        </li>
    }
</ul>
